<?php

namespace soullified\lifesoundtrackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * songtrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class songtrackRepository extends EntityRepository
{
}
