<?php

namespace soullified\boardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * dashboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dashboardRepository extends EntityRepository
{
}
