<?php

namespace soullified\boardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * upvotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class upvotesRepository extends EntityRepository
{
}
