<?php

namespace soullified\profilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * friendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class friendRepository extends EntityRepository
{
}
