<?php

namespace soullified\profilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * friendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class friendshipRepository extends EntityRepository
{
}
