<?php

namespace soullified\profilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends EntityRepository
{
}
